Options:
  ModelName: prodXS_data
  InputFile: workspaces/WS-HGam-ProdXS.root
  Dataset:   combData
  NPoints:   100

ParametersOfInterest:
  mu_ggH: [  0.50, 1.30, '#sigma / #sigma_{SM} (ggH)' ]
  mu_VBF: [  0.90, 2.10, '#sigma / #sigma_{SM} (VBF)' ]
  mu_VH:  [  0.30, 2.50, '#sigma / #sigma_{SM} (VH)'  ]
  mu_ttH: [ -0.30, 1.05, '#sigma / #sigma_{SM} (ttH)' ]
  #mu_WH:  [-0.50, 2.50, '#sigma / #sigma_{SM} (WH)'  ]
  #mu_ZH:  [-0.75, 4.00, '#sigma / #sigma_{SM} (ZH)'  ]
