Options:
  ModelName:  prodRatios_data
  InputFile:  workspaces/data/WS-HGam-XSratio.root
  Dataset:    combData
  Snapshot:   ucmles
  NPoints:    100
  Tolerance:  1.0E-04

ParametersOfInterest:
  mu_ggH:      [  0.55, 1.00, '#mu_{ggH}' ]
  muRatio_VBF: [  1.70, 3.80, '#mu_{VBF} / #mu_{ggH}' ]
  muRatio_VH:  [ -0.30, 2.5,  '#mu_{VH} / #mu_{ggH}'  ]
  muRatio_top: [ -0.10, 1.70, '#mu_{top} / #mu_{ggH}' ]

