Options:
  ModelName:  globalMu
  InputFile:  workspaces/AsimovOnly/WS-HGam-muLegacy.root
  Dataset:    AsimovSB
  NPoints:    100
  Tolerance:  1.0E-03

ParametersOfInterest:
  mu: [ 0.75, 1.40, '#mu' ]
