Options:
  InputFile: workspaces/WS-HGam-muLegacy.root
  Dataset:   AsimovSB
  NPoints:   50
  ModelName: muLegacy

ParametersOfInterest:
  mu_ggH: [ 0.60, 1.40, '#mu_{ggH}' ]
  mu_VBF: [ 0.00, 2.00, '#mu_{VBF}' ]
  mu_WH:  [-1.00, 4.00, '#mu_{WH}'  ]
  mu_ZH:  [-1.00, 4.00, '#mu_{ZH}'  ]
  mu_ttH: [-0.50, 2.50, '#mu_{ttH}' ]
