Options:
  InputFile: workspaces/WS-HGam-muRatios.root
  Dataset:   AsimovSB
  NPoints:   100
  ModelName: muRatios
  Tolerance: 1.0E-03

ParametersOfInterest:
  mu_ggH: [ 0.70, 1.50, '#mu_{ggH}' ]
  muRatio_VBF: [ 0.40, 2.00, '#mu_{VBF} / #mu_{ggH}' ]
  muRatio_VH:  [-0.50, 3.00, '#mu_{VH} / #mu_{ggH}'  ]
  muRatio_top: [ 0.00, 2.00, '#mu_{top} / #mu_{ggH}' ]
  #muRatio_ttH: [ 0.00, 2.00, '#mu_{ttH} / #mu_{ggH}' ]
  #muRatio_WH:  [-0.50, 3.00, '#mu_{WH} / #mu_{ggH}'  ]
  #muRatio_ZH:  [-0.80, 4.00, '#mu_{ZH} / #mu_{ggH}'  ]
