Options:
  InputFile: workspaces/WS-HGam-STXSMerged.root
  Dataset:   AsimovSB
  NPoints:   100
  ModelName: muSTXS

ParametersOfInterest:
  mu_gg2H_0J:               [  0.40,  1.60, '#sigma / #sigma_{SM} (ggH, 0J)' ]
  mu_gg2H_1J_ptH_0_60:      [ -1.00,  3.00, '#sigma / #sigma_{SM} (ggH, 1J Low)' ]
  mu_gg2H_1J_ptH_60_120:    [ -0.50,  2.50, '#sigma / #sigma_{SM} (ggH, 1J Med)' ]
  mu_gg2H_1J_ptH_120_200:   [ -1.00,  3.00, '#sigma / #sigma_{SM} (ggH, 1J High)' ]
  mu_gg2H_1J_ptH_gt200:     [ -3.00,  5.00, '#sigma / #sigma_{SM} (ggH, 1J BSM)' ]
  mu_gg2H_ge2J_ptH_0_60:    [ -3.00,  5.00, '#sigma / #sigma_{SM} (ggH, 2J Low)' ]
  mu_gg2H_ge2J_ptH_60_120:  [ -2.00,  4.00, '#sigma / #sigma_{SM} (ggH, 2J Med)' ]
  mu_gg2H_ge2J_ptH_120_200: [ -2.00,  4.00, '#sigma / #sigma_{SM} (ggH, 2J High)' ]
  mu_gg2H_ge2J_ptH_gt200:   [ -1.00,  3.00, '#sigma / #sigma_{SM} (ggH, 2J BSM)' ]
  mu_gg2H_VBFTOPO:          [ -3.00,  5.00, '#sigma / #sigma_{SM} (ggH, VBFTopo)' ]
  mu_qq2Hqq_VBFTOPO:        [ -0.50,  2.50, '#sigma / #sigma_{SM} (qqH, VBFTopo)' ]
  mu_qq2Hqq_VH2JREST:       [ -3.00,  5.00, '#sigma / #sigma_{SM} (qqH, VH2J + REST)' ]
  mu_qq2Hqq_pTjet1_gt200:   [ -3.00,  5.00, '#sigma / #sigma_{SM} (qqH, BSM)' ]
  mu_qq2Hlnu_pTV_0_150:     [ -1.00,  5.00, '#sigma / #sigma_{SM} (WH, p_{T}^{V} < 150 GeV)' ]
  mu_qq2Hlnu_pTV_gt150:     [ -2.00,  5.00, '#sigma / #sigma_{SM} (WH, p_{T}^{V} > 150 GeV)' ]
  mu_qq2Hll:                [ -1.00,  4.00, '#sigma / #sigma_{SM} (ZH)' ]
  mu_ttH:                   [  0.00,  2.00, '#sigma / #sigma_{SM} (ttH)' ]
